---
# tasks file for roles/java

- name: system packages | install java jre
  become: true
  yum:
    name: "java-{{ item }}-openjdk"
    state: present
  with_items: "{{ java_jre_versions }}"

- name: system packages | install java jdk
  become: true
  yum:
    name: "java-{{ item }}-openjdk-devel"
    state: present
  when: java_jdk_install
  with_items: "{{ java_jre_versions }}"
